### ISSUE TITLE
map commit references

### ISSUE THREAD

**Issue by glensc** [fragglet/agito#4]
i thought to share this. the snippet will map `rXXX` and `[XXX]` commit references (from [Trac](https://trac.edgewall.org/wiki/TracLinks#Overview)) to git hashes (truncated to 8 chars)

```python
def replace_vcs_commits(path, entry, message):
    def substitute(matchobj):
        payload = matchobj.group(1)
        commit = agito.get_commit(path, payload)

        if commit is None:
            print("No commit matches " + repr(payload))
            return matchobj.group(0) # no replacement
        elif commit:
            # truncat hash to 8 chars
            return commit[0:8]
        else:
            print("Cannot resolve %s" % payload)
            return matchobj.group(0) # no replacement

    for regexp in (\
        (r"r([0-9.]+)"),
        (r"\[([0-9]+)\]"),
        ):
        message = re.compile(regexp).sub(lambda m: substitute(m), message)

    return message
```

ps: I really liked your tool that it's written in Python and easily extendable, so i packaged it for [pld-linux](https://github.com/pld-linux/agito). Would you please tag (make release) so it's version would mean something.

**Comment by fragglet** [comment]
Interesting - please feel free to send a pull request for this.

**Comment by glensc** [comment]
how exactly? you mean provide default implementation as `agito.replace_vcs_commits`?

**Comment by glensc** [comment]
also, would you mind tagging current code as `1.0` or `0.1.0` or something?

**Comment by fragglet** [comment]
Sure, I can tag but I figured you'd want to add your function in before I do that - usual way to do that in Github is to send a pull request :)

Expect a couple of comments though.

**Comment by glensc** [comment]
i had an vision you'd want to tag previous code first :)
sure, i'll send PR after i've done some more testing, like multiple commit refs on same line
